### ISSUE TITLE
Day6

### ISSUE THREAD

**Issue by munmust** [munmust/st#7]
##  label都有哪些作用？并举相应的例子说明
	label标签通常写在表单内，关联一个控件
	for 属性用来关联表单，accesskey属性设置快捷键
```javascript
<input type="button" id="btn">
<label for="btn">Button</label>

<style>
input[type='button'] {
  display: none;
}

label {
  display: inline-block;
  padding: 10px 20px;
  background: #456;
  color: #fff;
  cursor: pointer;
  box-shadow: 2px 2px 4px 0 rgba(0,0,0,.3);
  border-radius: 2px;
}
</style>
```
##  用css创建一个三角形，并简述原理
	普通三角形：不设置宽高，设置border的宽度，将三个border设置不可见，就可以得到三角形
	边框三角形：按照普通三角形制作三角形，之后利用伪元素其中一个比另一个大一点，之后使用绝对定位进行移动
```css
.rect{
			width: 0;
      height: 0;
      background-color: #fff;
      border-right: 100px solid transparent;
      border-left: 100px solid transparent;
      border-top: 100px solid rgb(29, 156, 194);
      border-bottom: 100px solid transparent;
}

<div id="blue"><div>

#blue {
    position:relative;
    width: 0;
    height: 0;
    border-width: 0 40px 40px;
    border-style: solid;
    border-color: transparent transparent blue;
}
#blue:after {
    content: "";
    position: absolute;
    top: 1px;
    left: -38px;
    border-width: 0 38px 38px;
    border-style: solid;
    border-color: transparent transparent yellow;
}
```
##  写一个去除制表符和换行符的方法
```javascript
function remoteSymbol(str){
	return str.replace(/[\t\n]/g,'');
}	
```

##	render函数中return如果没有使用()会有什么问题
正常来说不会出现问题，但是如果return后跟的是换行，在下面一行才写输出结果会出现错误
	在我们使用jsx写完react的时候，babel会将jsx语法编译成js，同时会在每一行自动添加分号（；），如果return后跟了换行，就会编译为return;，会报：Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null（渲染没有返回任何内容。这通常意味着缺少return语句。或者，为了不渲染，返回null）;
写法
```javascript
	const header = () =>{
		return (
			<Header>
				header
			</Header>
		)
	}
	const header = () => {
		return <Header>
				header
			</Header>
	}
```
##	componentWillUpdate可以直接修改state的值吗
	componentWillUpdate中可以直接修改state的,不过不推荐，会打断生命周期的执行，更新完state之后会再次执行componentWillUpdate生命周期，处理不好会导致死循环。
	ps:当你传入的是一个对象的话会造成死循环，当你传入的是一个函数((preState,props)=>{}),可以通过条件来避免死循环。在条件满足的情况下才混进行修改，否则不修改。避免了死循环。
##	React-Router怎么获取URL的参数
-	this.props.location.query.XX,
-	this.props.match.params.XX,
-	this.props.location.search 
-	useParams钩子

##	在history模式中push和replace有什么区别
-	push会新增一条新的历史纪录 history会增加
-	repalce会替换当前历史记录	history不会增加
